sonata-project/sonata-doctrine-extensions

README.md
=> Simplify composer require documentation

tests/Types/JsonTypeTest.php
I am targetting this branch, because its BC
typo
=> fixed typo

phpunit.xml.dist, src/Types/JsonType.php
=> Add whitelist to phpunit.xml.dist

composer.json
I am targeting this branch, because this is for the next major release.
There is not so much to do for the next major release, because there is not so many code in here ;)
=> Prepare major

.travis.yml, CONTRIBUTING.md, composer.json
```markdown
- Rollback to PHP 5.6 as minimum support.
```
=> DevKit updates for 1.x branch

.gitattributes, .styleci.yml, .travis.yml, .travis/before_install_test.sh, .travis/install_test.sh, CONTRIBUTING.md
=> Manual merge master with 1.x

.php_cs.dist, .travis.yml, .travis/check_relevant_lint.sh, .travis/install_test.sh, tests/Types/JsonTypeTest.php
=> Manual merge

src/Types/JsonType.php, tests/Types/JsonTypeTest.php, tests/bootstrap.php
After dev-kit PR https://github.com/sonata-project/sonata-doctrine-extensions/pull/75, this fixes the build
=> Fix coding standards

README.md
I am targeting this branch, because this is a doc fix.
Use the same layout as for the other bundles.
=> Adopt new README layout

src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php, src/Bridge/Symfony/Resources/config/services.xml
I am targeting this branch, because this fixes broken DI.
```markdown
Fix class namespace and services loading
```
This PR fixes broken stuff due to last migration from SonataCoreBundle.
=> fix(DI): class namespace and services loading

src/Document/BaseDocumentManager.php, src/Document/BasePHPCRManager.php, src/Entity/BaseEntityManager.php
```markdown
- Removed `@mixin`s from classes
```
They caused some problems, so they should be removed.
cc @OskarStark
=> Removed @mixin's from classes

src/Test/EntityManagerMockFactoryTrait.php
Closes #156
```markdown
- Add `EntityManagerMockFactoryTrait`
```
=> Add EntityManagerMockFactoryTrait

.github/workflows/qa.yml, phpstan-baseline.neon, phpstan.neon.dist, src/Adapter/ORM/DoctrineORMAdapter.php, src/Adapter/PHPCR/DoctrinePHPCRAdapter.php, src/Document/BaseDocumentManager.php, src/Test/EntityManagerMockFactory.php
Improve code quality by running phpstan 🚀 
I am targeting this branch, because this is will help to improve code quality for the stable branch.
```markdown
- Fix typo in class name
```
=> Add phpstan checks

src/Document/BaseDocumentManager.php, src/Document/BasePHPCRManager.php, src/Entity/BaseEntityManager.php, src/Model/BaseManager.php, src/Model/ManagerInterface.php
This is my first try with generics in PHP. I used https://github.com/phpstan/phpstan-src/blob/e7581e7f560b9538bc7af8dadcd6cd1c7b1ff3b9/stubs/ReflectionClass.php as a blueprint.
```markdown
- Add generic information to `ManagerInterface`
```
=> Add generic information

.travis.yml, composer.json, tests/Adapter/ORM/DoctrineORMAdapterTest.php, tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php, tests/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPassTest.php, tests/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPassTest.php, tests/Mapper/ORM/DoctrineORMMapperTest.php, tests/Types/JsonTypeTest.php
I am targeting this branch, because this does not contain BC break
```markdown
Bump SF to 4.4 and PHPUnit to 8 in CI
```
=> Bump to SF 4.4 & PHPUnit version 8

.github/workflows/qa.yml, composer.json, src/Adapter/ORM/DoctrineORMAdapter.php, src/Adapter/PHPCR/DoctrinePHPCRAdapter.php, src/Document/BasePHPCRManager.php, src/Mapper/ORM/DoctrineORMMapper.php, src/Model/BaseManager.php, src/Test/EntityManagerMockFactory.php, src/Test/EntityManagerMockFactoryTrait.php, tests/Adapter/ORM/DoctrineORMAdapterTest.php, tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php, tests/Document/BaseDocumentManagerTest.php, tests/Entity/BaseEntityManagerTest.php, tests/Model/BaseManagerTest.php
```markdown
- Fixed doctrine deprecations
```
=> Fix doctrine deprecations

src/Test/EntityManagerMockFactoryTrait.php
I am targeting this branch, because this is for tests only.
```markdown
- Add more stub methods to `EntityManagerMockFactoryTrait`
```
=> Add more stub methods to test factory

src/Adapter/AdapterChain.php, src/Adapter/AdapterInterface.php, src/Adapter/ORM/DoctrineORMAdapter.php, src/Adapter/PHPCR/DoctrinePHPCRAdapter.php, tests/Adapter/AdapterChainTest.php, tests/Adapter/ORM/DoctrineORMAdapterTest.php, tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php
Fix some API violations.
I am targeting this branch, because these changes respect BC.
```markdown
- Fixed returning `void` from methods which are intended to return values;
- Fixed weak check at `ModelManager::getNormalizedIdentifier()`.
```
=> Fix some API violations

tests/App/Kernel.php
I am targeting this branch, because this is pedantic.
=> Avoid deprecation

composer.json, src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php, src/Bridge/Symfony/Resources/config/doctrine_orm.php, src/Bridge/Symfony/Resources/config/doctrine_orm.xml, src/Bridge/Symfony/Resources/config/doctrine_phpcr.php, src/Bridge/Symfony/Resources/config/doctrine_phpcr.xml, src/Bridge/Symfony/Resources/config/mapper_orm.php, src/Bridge/Symfony/Resources/config/mapper_orm.xml, src/Bridge/Symfony/Resources/config/services.php, src/Bridge/Symfony/Resources/config/services.xml, tests/Bridge/Symfony/DependencyInjection/SonataDoctrineExtensionTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6284
=> Move internal configuration to PHP

src/Model/BaseManager.php
Ref: https://github.com/sonata-project/sonata-doctrine-extensions/pull/303, https://github.com/sonata-project/sonata-doctrine-extensions/pull/304
=> Specify phpstan var type

src/Model/ManagerInterface.php, src/Model/PageableManagerInterface.php
```markdown
- Add type hints to interfaces
```
=> Add type hints to interfaces

src/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPass.php, src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php, tests/Bridge/Symfony/DependencyInjection/SonataDoctrineExtensionTest.php
checkout https://github.com/sonata-project/sonata-doctrine-extensions/pull/219 as reference
=> handle doctrine_phpcr in a propper way

phpstan-baseline.neon, src/Adapter/ORM/DoctrineORMAdapter.php, src/Adapter/PHPCR/DoctrinePHPCRAdapter.php, src/Model/BaseManager.php, src/Model/ClearableManagerInterface.php, src/Model/ManagerInterface.php, tests/Model/BaseManagerTest.php
```markdown
- Added `ClearableManagerInterface` to be able to clear the Manager in an easy way.
```
=> Add ClearableManagerInterface
