sonata-project/sonata-doctrine-extensions

- composer.json
- phpunit.xml.dist
I am targetting this branch, because dropping versions of Symfony is major.
```markdown
- compatibility with symfony 2.7 was dropped
```
> Drop old versions of Symfony

- .gitignore
- src/Types/JsonType.php
I am targetting this branch, because this is a pedantic change.
Removes platform entries and old unused files.
Refs: https://github.com/sonata-project/dev-kit/issues/211
> Cleanup gitignore file

- src/Adapter/AdapterChain.php
- src/Adapter/AdapterInterface.php
- src/Adapter/ORM/DoctrineORMAdapter.php
- src/Adapter/PHPCR/DoctrinePHPCRAdapter.php
- src/Document/BaseDocumentManager.php
- src/Document/BasePHPCRManager.php
- src/Entity/BaseEntityManager.php
- src/Model/BaseManager.php
- src/Model/ManagerInterface.php
- src/Model/PageableManagerInterface.php
By loading the deprecated type, we make sure the class alias they
contains exist, so that code type hinting against the old type
accepts the new. This is necessary because type hinting does not trigger
autoload, since it usually does not need to.
Contrary to #107, the alias will not be created if sonata/core-bundle is not installed, which should not happen since code type hinting against an interface from that package is supposed to require it explicitely.
Fixes #108, Closes #107 
```markdown
- crash about type hinting issues with AdapterInterface
```
> Trigger deprecated types autoload

- src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php
invalid doctrine_phpcr config filename loading in SonataDoctrineExtension
> [BUG] fix invalid filename for config doctrine_phpcr.xml

- src/Types/JsonType.php
This is because of the new `strict_types` policy
Fixes #116
```markdown
- crash when decoding null value as JSON
```
> Cast nullable value to string

- UPGRADE-1.x.md
- composer.json
- src/Types/JsonType.php
- tests/Types/JsonTypeTest.php
`doctrine/dbal` has an implementation of this now.
```markdown
- `Sonata\Doctrine\Types\JsonType`, in favor of `Doctrine\DBAL\Types\JsonType`
```
> Deprecate JsonType

- composer.json
- src/Bridge/Symfony/Bundle/SonataDoctrineBundle.php
- src/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPass.php
- tests/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPassTest.php
Closes https://github.com/sonata-project/SonataCoreBundle/pull/679
```markdown
- Adapters are not being injected on the adapter chain.
- `sonata_urlsafeid` twig filter is working again
```
This is related to https://github.com/sonata-project/SonataCoreBundle/pull/679
When this bridge bundle is not loaded, then this alias makes this work: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/CoreBundle/DependencyInjection/SonataCoreExtension.php#L80.
When you enable this bridge (as the deprecation message says), you start getting errors on the urlsafeid twig function, because the adapters are not loaded correctly.
Not sure if we should also do a PR on coreBundle to disable the compiler pass if this bundle is enabled. Probably we …
> Move compiler pass from CoreBundle

- src/Model/PageableManagerInterface.php
Moving the interface to this repo was wrong https://github.com/sonata-project/sonata-doctrine-extensions/pull/82.
We should use https://github.com/sonata-project/SonataDatagridBundle/blob/3.x/src/Pager/PageableInterface.php instead which does all pagination stuff.
```markdown
- Deprecated `Sonata\Doctrine\Model\PageableManagerInterface`
```
> Deprecated PageableManagerInterface

- src/Bridge/Symfony/Bundle/SonataDoctrineBundle.php
- src/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPass.php
- src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php
- src/Bridge/Symfony/Resources/config/mapper_orm.xml
- src/Mapper/Builder/ColumnDefinitionBuilder.php
- src/Mapper/Builder/OptionsBuilder.php
- src/Mapper/DoctrineCollector.php
- src/Mapper/ORM/DoctrineORMMapper.php
- tests/Mapper/DoctrineCollectorTest.php
- tests/Mapper/ORM/DoctrineORMMapperTest.php
Move all mapper classes from EasyExtends to this bundle.
Refs https://github.com/sonata-project/SonataEasyExtendsBundle/pull/209
I am targeting this branch, because this feature is BC.
```markdown
- Added `DoctrineORMMapper` to manipulate doctrine entity relations
```
> Created new DoctrineMapper

- src/Entity/BaseEntityManager.php
- tests/Entity/BaseEntityManagerTest.php
Make BaseEntityManager::getRepository returns an Doctrine\ORM\EntityManager
I am targeting this branch, because this should have no effect on executed code. The goal is to fix static analysis of php code as Doctrine\Common\Persistence\ObjectRepository interface does not have the createQueryBuilder method.
Fix BaseEntityManager::getRepository return type
```markdown
- Fix BaseEntityManager::getRepository return type
```
> Fix static analysis of ObjectRepository interface

- src/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPass.php
- src/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPass.php
- tests/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPassTest.php
- tests/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPassTest.php
If we use PHPCR without ORM ( like https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle ) we have this 2 errors :
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
You have requested a non-existent service "sonata.doctrine.mapper". 
```
And
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
The service "sonata.doctrine.model.adapter.chain" has a dependency on a non-existent service "sonata.doctrine.adapter.doctrine_orm". 
```
I am targeting this branch, because this is a patch with BC.
```markdown
- Using with only PHPCR without ORM
```
> fix using phpcr without orm

- src/Entity/BaseEntityManager.php
- tests/Entity/BaseEntityManagerTest.php
cannot mock a final method for testing
Closes #142 
```markdown
- Remove the final modifier for the `getRepository` method
```
> fix(manager): remove final modifier for the method get repository

- composer.json
- src/Model/BaseManager.php
- src/Test/EntityManagerMockFactory.php
- tests/Adapter/ORM/DoctrineORMAdapterTest.php
- tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php
- tests/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPassTest.php
- tests/Mapper/ORM/DoctrineORMMapperTest.php
- tests/Types/JsonTypeTest.php
The change in the BaseManager is because [`ObjectRepository::findOneBy`](https://github.com/doctrine/persistence/blob/1.1.x/lib/Doctrine/Common/Persistence/ObjectRepository.php#L53) only receives one parameter.
I am targeting this branch, because is BC.
```markdown
- Added support for Symfony 5
- Support for Symfony < 3.4
- Support for Symfony >= 4, < 4.2
```
> Add support symfony 5

- src/Model/BaseManager.php
I should have included this in https://github.com/sonata-project/sonata-doctrine-extensions/pull/152
I am targeting this branch, because is BC.
```markdown
- Passing a second argument to `BaseManager::findOneBy`
```
> Add deprecation for findOneBy with two arguments

- src/Mapper/Builder/OptionsBuilder.php
- tests/Mapper/Builder/OptionsBuilderTest.php
The idea (https://github.com/sonata-project/sonata-doctrine-extensions/issues/172) is to create some methods that make using `OptionsBuilder` more developer-friendly. 
The checks are based on [doctrine docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/association-mapping.html#association-mapping). 
Closes #172
```markdown
- Added some explicit methods to `OptionsBuilder`
- `OptionsBuilder::create` method
```
I added:
- `createOneToOne`
- `createOneToMany`
- `createManyToOne`
- `createManyToMany`
- `mappedBy `
- `inversedBy`
- `addJoinTable`
- `addOrder`
- `addJoin`
- `cascade`
- `orphanRemoval `
> Make OptionsBuilder API more explicit

- src/Document/BaseDocumentManager.php
- src/Document/BasePHPCRManager.php
- src/Entity/BaseEntityManager.php
- src/Model/BaseManager.php
- src/Model/ManagerInterface.php
- tests/Model/BaseManagerTest.php
These changes are focused on narrow the API.
I am targeting this branch, because these changes break BC.
```markdown
- Added missing argument and return type declarations at `Sonata\Doctrine\Document\BaseDocumentManager`, `Sonata\Doctrine\Document\BasePHPCRManager`, `Sonata\Doctrine\Entity\BaseEntityManager`, `Sonata\Doctrine\Model\BaseManager`, `Sonata\Doctrine\Model\ManagerInterface`.
```
> Narrowing API

- src/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPass.php
> Fix variable inconsistencies

- composer.json
Drop support for php:7.1.
```markdown
- Removed support for php:7.1.
```
> Drop support for php:7.1

- composer.json
Fix constraint for "doctrine/phpcr-odm", removed unreachable range `^2.0` which has no available release.
See https://github.com/doctrine/phpcr-odm/releases.
> Fix constraint for "doctrine/phpcr-odm"

- composer.json
Allow version 2 for "doctrine/persistence".
```markdown
- Added support for "doctrine/persistence:^2.0".
```
> Allow "doctrine/persistence:^2.0"

- UPGRADE-1.x.md
- src/Bridge/Symfony/SonataDoctrineBundle.php
Deprecated `Sonata\Doctrine\Bridge\Symfony\Bundle\SonataDoctrineBundle`.
Triggered by sonata-project/SonataAdminBundle#6173.
```markdown
- Added `Sonata\Doctrine\Bridge\Symfony\SonataDoctrineBundle`.
- Deprecated `Sonata\Doctrine\Bridge\Symfony\Bundle\SonataDoctrineBundle` in favor of `Sonata\Doctrine\Bridge\Symfony\SonataDoctrineBundle`.
```
> Deprecate `Sonata\Doctrine\Bridge\Symfony\Bundle\SonataDoctrineBundle`

- UPGRADE-1.x.md
- composer.json
- src/Mapper/DoctrineCollector.php
- src/Mapper/ORM/DoctrineORMMapper.php
- tests/App/Entity/TestEntity.php
- tests/App/Entity/TestInheritanceEntity.php
- tests/App/Entity/TestRelatedEntity.php
- tests/App/Kernel.php
- tests/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPassTest.php
- tests/Mapper/DoctrineCollectorTest.php
- tests/Mapper/ORM/DoctrineORMMapperTest.php
I am targeting this branch, because without this fix it is imposible to use this feature.
I am trying to use this bundle to generate dynamic mapping here: https://github.com/Runroom/RunroomSamplesBundle/blob/master/src/DependencyInjection/RunroomSamplesExtension.php#L43
I had to stop using it and return to the EasyExtendsBundle way. Why? Because I keep getting an error similar to this: https://stackoverflow.com/questions/44323315/symfony-compiler-pass-i-want-to-add-method-call-to-logger-service 
I think the problem is trying to use the compiler pass to add calls with objects without using definitions: https://github.com/sonata-project/sonata-doctrine-extensions/blob/1.x/src/Bridge/Symfony/DependencyInjection/Compiler/MapperCompilerPass.php#L41
That `$options` without this patch is an …
> Fix addAssociation, addDiscriminatorColumn and addOverride on DoctrineCollector

- composer.json
- phpstan.neon.dist
- src/Bridge/Symfony/Bundle/SonataDoctrineBundle.php
- src/Bridge/Symfony/SonataDoctrineSymfonyBundle.php
Add `SonataDoctrineSymfonyBundle` in order to be compatible with Symfony Flex.
```markdown
- Added `Sonata\Exporter\Bridge\Symfony\SonataDoctrineSymfonyBundle` alias in order to fix Symfony Flex autodiscovery.
```
> Add `SonataDoctrineSymfonyBundle` in order to be compatible with Symfony Flex

- src/Bridge/Symfony/Bundle/SonataDoctrineBundle.php
There is a conflict with the class names, I couldn't come up with a better name 😬
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6264
```markdown
- Fixed conflict with class names.
```
> Fix conflict with class names

- composer.json
Ref: https://github.com/sonata-project/dev-kit/issues/1069
We are dropping support for doctrine/mongodb-odm <2.0, this allows us to not install `alcaeus/mongo-php-adapter` in GA for tests.
I am targeting this branch, because these changes are BC.
```markdown
- Remove support for `doctrine/mongodb-odm` <2.0
```
> Add conflict with doctrine/mongodb-odm <2.0

- src/Test/EntityManagerMockFactoryTrait.php
```markdown
- Compatibility with PHPUnit 9 
```
It makes no sense to have this abstract method.
> Remove createMock abstract method

- src/Test/EntityManagerMockFactoryTrait.php
I am targeting this branch, because BC.
```markdown
- `EntityManagerMockFactoryTrait` now mocks all the basics methods of the QueryBuilder
```
> Mock basic method of the QueryBuilder
